name: MAAK_ROSTAR_FILE
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311h540bb41_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - intel-openmp=2025.0.0=haa95532_1164
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - numexpr=2.14.1=py311h7660c64_0
  - numpy=2.3.5=py311h050da96_0
  - numpy-base=2.3.5=py311h1e017a8_0
  - openssl=3.0.18=h543e019_0
  - pandas=2.3.3=py311h42c1672_1
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311haa95532_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - et-xmlfile==2.0.0
      - openpyxl==3.1.5
prefix: C:\Users\mverb\anaconda3\envs\MAAK_ROSTAR_FILE
